ASM_OBJ += 

C_OBJ += $(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/TOPPERS_HAL_layer.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o \
		$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o 

CXX_OBJ += 

INCLUDE_PATHS += -I. \
		-I$(STM32_LIB_DIR)/Drivers/STM32F7xx_HAL_Driver/Inc

